### PR TITLE
Fix RN warning.

### PR DESCRIPTION
**Pull request by jay0lu**
RN warning about adding key for list items.

### CODE REVIEW

**Comment by RangerMauve** [comment]
I guess this will have to do until we have something better for #1.

Thanks for the PR!

**Comment by RangerMauve** [comment]
Released in 1.0.4

**Comment by jay0lu** [comment]
Use columns + rows to getkeys? Why index is not good enough?

**Comment by RangerMauve** [comment]
https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by jay0lu** [comment]
Noooo, I've been using index for a lot...

**Pull request merged**
